import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Map as MapIcon,
    GraduationCap,
    Mic,
    LayoutDashboard
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { MOCK_BLOCK_DATA } from '@/lib/rpAnalytics';
import { MentorCopilot } from '@/components/rp/MentorCopilot';
import { SpaceScene } from '@/components/layout/SpaceScene';
import { CRPDashboard } from '@/components/rp/CRPDashboard';
import { ARPDashboard } from '@/components/rp/ARPDashboard';
import { BRPDashboard } from '@/components/rp/BRPDashboard';
import { LanguageSwitcher } from '@/components/common/LanguageSwitcher';
import { jsPDF } from 'jspdf';

type RPRole = 'BRP' | 'CRP' | 'ARP';

export default function ResourcePersonDashboard() {
    const [role, setRole] = useState<RPRole>('BRP');
    const [selectedCluster, setSelectedCluster] = useState(MOCK_BLOCK_DATA.clusters[0]);
    const [showMentorCopilot, setShowMentorCopilot] = useState(false);
    const [isExporting, setIsExporting] = useState(false);

    const triggerDownload = (fileName: string, content: string, title: string) => {
        const doc = new jsPDF();

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.setTextColor(0, 102, 204);
        doc.text('SHIKSHALOKAM RESOURCE COMMAND CENTER', 20, 20);

        doc.setLineWidth(0.5);
        doc.line(20, 25, 190, 25);

        // Report Info
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text(title, 20, 40);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);
        doc.text(`Role: ${role}`, 20, 50);
        doc.text(`Cluster: ${selectedCluster.name}`, 20, 57);
        doc.text(`Date: ${new Date().toLocaleString()}`, 20, 64);

        // Body
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text('Summary of Analytics:', 20, 80);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        const splitText = doc.splitTextToSize(content, 170);
        doc.text(splitText, 20, 90);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Resource Intelligence Engine v2.0 - Strictly Confidential', 20, 280);

        doc.save(fileName);
    };

    const handleGenerateReport = () => {
        setIsExporting(true);
        const reportType = role === 'BRP' ? 'Block Deployment Report' : role === 'ARP' ? 'Academic Mastery Analytics' : 'Field Visit Log';
        const fileName = `${role}_Report_${selectedCluster.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;

        const getRoleSpecificContent = () => {
            switch (role) {
                case 'BRP':
                    return `This is a synthesized Block Operations Report for ${selectedCluster.name}. 
                    
ADMINISTRATIVE SUMMARY:
- Personnel Deployment: The cluster is currently at ${selectedCluster.overallHealth}% staffing efficiency.
- Infrastructure Status: ${selectedCluster.needsSupportCount} schools have flagged critical maintenance requirements.
- Compliance: MDM and UDISE verification is at 88% completion for the current quarter.
                    
RECOMMENDATION:
Prioritize the transfer of 2 surplus teachers to schools in the western sector to balance the Pupil-Teacher Ratio (PTR).`;
                case 'ARP':
                    return `This is a synthesized Academic Mastery Analytics report for ${selectedCluster.name}.
                    
PEDAGOGICAL INSIGHTS:
- Concept Mastery: Grade 7 Math (Fractions) remains a cluster-wide gap with <45% mastery.
- Training Impact: The recent 'Experiential Science' workshop has improved classroom engagement by 15%.
- Resource Usage: Top performing school, ${selectedCluster.topPerformingSchool}, shows 92% utilization of digital library kits.
                    
RECOMMENDATION:
Conduct a diagnostic remediation session for Grade 7 teachers focusing on visual aids for abstract mathematical concepts.`;
                case 'CRP':
                    return `This is a synthesized Field Visit & Observation Log for ${selectedCluster.name}.
                    
FIELD SUMMARY:
- Visit Velocity: 12 schools visited this month with an average observation score of 72%.
- Classroom Management: Significant improvement noted in 'Student Voice' and interactive questioning techniques.
- Peer Mentorship: 2 new 'Math Circle' peer groups established across schools in the northern zone.
                    
RECOMMENDATION:
Schedule a follow-up visit to the underperforming schools to reassess the implementation of the NIPUN Bharat pedagogical guidelines.`;
                default:
                    return `Synthesized report for ${selectedCluster.name}. All data is synchronized with the Resource Central Repository.`;
            }
        };

        toast.promise(
            new Promise((resolve) => setTimeout(resolve, 2500)),
            {
                loading: `Synthesizing ${reportType} for ${selectedCluster.name}...`,
                success: () => {
                    setIsExporting(false);
                    const mockContent = getRoleSpecificContent();
                    triggerDownload(fileName, mockContent, reportType);
                    return `${reportType} for ${selectedCluster.name} has been generated.`;
                },
                error: () => {
                    setIsExporting(false);
                    return 'Infrastructure error: Failed to generate report.';
                },
            }
        );
    };

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-[#020617] relative overflow-x-hidden p-6 md:p-12 mb-12 selection:bg-brand-blue/30 font-sans text-slate-900 dark:text-slate-100 transition-colors duration-500">
            <div className="fixed inset-0 z-0 pointer-events-none">
                <div className="hidden dark:block">
                    <SpaceScene />
                    <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#020617]/40 to-[#020617]" />
                </div>
                <div className="dark:hidden absolute inset-0 bg-slate-50 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-100 via-transparent to-transparent opacity-40" />
            </div>

            <div className="max-w-7xl mx-auto relative z-10 space-y-12">
                {/* Header Section */}
                <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-10 pb-10 border-b border-slate-200 dark:border-white/5">
                    <div className="space-y-4">
                        <div className="flex items-center gap-6">
                            <div className="relative group">
                                <div className="absolute inset-0 bg-brand-blue/40 blur-2xl rounded-full animate-pulse group-hover:bg-brand-blue/60 transition-all" />
                                <div className="w-16 h-16 rounded-[1.5rem] bg-gradient-to-br from-brand-blue to-blue-700 flex items-center justify-center relative shadow-[0_0_50px_rgba(37,99,235,0.4)] border border-white/20 transform group-hover:rotate-6 transition-transform">
                                    <LayoutDashboard className="w-8 h-8 text-white" />
                                </div>
                            </div>
                            <div className="space-y-1">
                                <h1 className="text-5xl md:text-6xl font-black font-orbitron tracking-tighter text-slate-900 dark:text-white uppercase leading-none">
                                    Resource <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-blue via-cyan-400 to-indigo-500">Command</span>
                                </h1>
                                <div className="flex items-center gap-3 mt-2">
                                    <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-green-500/10 border border-green-500/20">
                                        <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                                        <span className="text-[10px] text-green-600 dark:text-green-400 font-black uppercase tracking-widest">Live Engine v2.0</span>
                                    </div>
                                    <span className="text-slate-400 text-xs font-bold tracking-[0.2em] uppercase">• {MOCK_BLOCK_DATA.name.toUpperCase()} REGION</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-6">
                        <div className="relative">
                            <select
                                value={selectedCluster.id}
                                onChange={(e) => {
                                    const cluster = MOCK_BLOCK_DATA.clusters.find(c => c.id === e.target.value);
                                    if (cluster) setSelectedCluster(cluster);
                                }}
                                className="bg-white/80 dark:bg-white/[0.03] border border-slate-200 dark:border-white/10 rounded-2xl px-6 py-3.5 text-sm font-black uppercase tracking-widest focus:outline-none focus:ring-2 focus:ring-brand-blue appearance-none pr-12 min-w-[220px] shadow-sm backdrop-blur-xl transition-all hover:bg-white dark:hover:bg-white/5"
                            >
                                {MOCK_BLOCK_DATA.clusters.map(c => (
                                    <option key={c.id} value={c.id} className="dark:bg-slate-900 dark:text-white">{c.name} Cluster</option>
                                ))}
                            </select>
                            <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-slate-400">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" /></svg>
                            </div>
                        </div>
                        <LanguageSwitcher />
                    </div>
                </div>

                {/* Role Switcher - Premium HUD Style */}
                <div className="inline-flex p-2 bg-white/90 dark:bg-black/40 backdrop-blur-3xl rounded-[2rem] border border-slate-200 dark:border-white/10 shadow-2xl relative overflow-hidden ring-1 ring-slate-200/50 dark:ring-white/5 w-fit mx-auto lg:mx-0">
                    <div className="absolute inset-0 bg-gradient-to-br from-brand-blue/[0.05] to-transparent pointer-events-none" />
                    {(['BRP', 'ARP', 'CRP'] as RPRole[]).map((r) => (
                        <button
                            key={r}
                            onClick={() => setRole(r)}
                            className={`
                                    flex items-center gap-3 relative px-10 py-4 rounded-[1.5rem] text-[10px] font-black uppercase tracking-[0.3em] transition-all duration-500 ease-out z-10
                                    ${role === r
                                    ? 'text-white shadow-[0_15px_30px_-5px_rgba(59,130,246,0.5)] bg-gradient-to-br from-brand-blue via-blue-600 to-indigo-600 transform scale-[1.02]'
                                    : 'text-slate-500 hover:text-slate-900 dark:hover:text-slate-300 hover:bg-slate-50 dark:hover:bg-white/5'
                                }
                                `}
                        >
                            {r === 'BRP' && <LayoutDashboard className="w-4 h-4 opacity-50" />}
                            {r === 'ARP' && <GraduationCap className="w-4 h-4 opacity-50" />}
                            {r === 'CRP' && <MapIcon className="w-4 h-4 opacity-50" />}
                            {r} Perspective
                            {role === r && (
                                <motion.div
                                    layoutId="role-glow"
                                    className="absolute inset-x-0 -bottom-1 h-px bg-white/40 blur-sm"
                                />
                            )}
                        </button>
                    ))}
                </div>

                {/* Main Content Area */}
                <div className="w-full">
                    <div className="bg-white/95 dark:bg-[#0A0F1E]/60 border border-slate-200 dark:border-white/5 rounded-[3.5rem] p-1 md:p-12 backdrop-blur-3xl relative overflow-hidden min-h-[600px] shadow-2xl dark:shadow-none">
                        <div className="absolute inset-0 bg-gradient-to-tr from-indigo-500/[0.02] via-transparent to-brand-blue/[0.02] pointer-events-none" />

                        {/* Dashboard Role Context Header */}
                        <div className="flex flex-col lg:flex-row lg:items-center justify-between mb-12 pb-10 border-b border-slate-100 dark:border-white/5 gap-8 relative z-10 px-4">
                            <div className="space-y-4">
                                <div className="flex items-center gap-5">
                                    <div className={`p-4 rounded-2xl shadow-xl transition-all duration-500 transform hover:rotate-6 ${role === 'CRP' ? 'bg-brand-blue/10 text-brand-blue' :
                                            role === 'ARP' ? 'bg-pink-500/10 text-pink-500' :
                                                'bg-purple-500/10 text-purple-500'
                                        }`}>
                                        {role === 'CRP' ? <MapIcon className="w-8 h-8" /> : role === 'ARP' ? <GraduationCap className="w-8 h-8" /> : <LayoutDashboard className="w-8 h-8" />}
                                    </div>
                                    <div>
                                        <h2 className="text-4xl font-black text-slate-900 dark:text-white font-orbitron tracking-tight leading-none uppercase">
                                            {role === 'BRP' ? 'Operations Center' :
                                                role === 'ARP' ? 'Academic Hub' :
                                                    'Mentorship Cockpit'}
                                        </h2>
                                        <p className="text-[10px] text-slate-500 dark:text-slate-500 font-black uppercase tracking-[0.4em] mt-2">
                                            Strategy & Deployment Engine
                                        </p>
                                    </div>
                                </div>
                                <p className="text-slate-500 dark:text-slate-400 text-sm font-medium max-w-2xl leading-relaxed italic pl-6 border-l-2 border-slate-200 dark:border-white/10">
                                    {role === 'BRP' ? 'Administrative oversight, resource allocation, and compliance monitoring across all clusters.' :
                                        role === 'ARP' ? 'Pedagogical planning, teacher training analytics, and learning outcome tracking.' :
                                            'Daily visit planning, classroom observation tools, and peer mentorship management.'}
                                </p>
                            </div>

                            <div className="flex items-center gap-4 relative z-10">
                                <Button
                                    size="lg"
                                    disabled={isExporting}
                                    className="bg-slate-900 text-white hover:bg-slate-800 dark:bg-white dark:text-black dark:hover:bg-slate-200 font-black uppercase tracking-[0.2em] text-[10px] h-16 px-10 shadow-2xl transition-all flex items-center gap-3 rounded-[1.5rem] relative overflow-hidden group"
                                    onClick={handleGenerateReport}
                                >
                                    <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent skew-x-[-20deg] animate-shimmer pointer-events-none" />
                                    {isExporting ? <div className="w-5 h-5 border-3 border-current border-t-transparent rounded-full animate-spin" /> : <div className="w-2.5 h-2.5 rounded-full bg-blue-500 animate-pulse" />}
                                    Export Analysis
                                </Button>
                                <Button
                                    size="icon"
                                    variant="outline"
                                    className="h-16 w-16 rounded-[1.5rem] border-slate-200 dark:border-white/10 bg-white/50 dark:bg-white/5 text-slate-400 hover:text-brand-blue hover:border-brand-blue/50 transition-all shadow-lg backdrop-blur-xl group"
                                    onClick={() => setShowMentorCopilot(true)}
                                >
                                    <Mic className="w-6 h-6 group-hover:scale-110 transition-transform" />
                                </Button>
                            </div>
                        </div>

                        {/* Dynamic Dashboard Content */}
                        <AnimatePresence mode="wait">
                            <motion.div
                                key={role + selectedCluster.id}
                                initial={{ opacity: 0, y: 30 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -30 }}
                                transition={{ type: "spring", stiffness: 100, damping: 20 }}
                                className="w-full relative z-10"
                            >
                                {role === 'CRP' && <CRPDashboard cluster={selectedCluster} />}
                                {role === 'ARP' && <ARPDashboard cluster={selectedCluster} />}
                                {role === 'BRP' && <BRPDashboard cluster={selectedCluster} />}
                            </motion.div>
                        </AnimatePresence>
                    </div>
                </div>
            </div >

            <AnimatePresence>
                {showMentorCopilot && (
                    <MentorCopilot onClose={() => setShowMentorCopilot(false)} />
                )}
            </AnimatePresence>
        </div >
    );
}
